### ISSUE TITLE
Panel inicial de carga de la App

### ISSUE THREAD

**Issue by mpardalm** [ArtichokeCore/Mikana-android#10]

**Comment by n1nj4t4nuk1** [comment]
Panel? Pero la carga de elementos inicial es bastante pequeña. Un panel de carga a penas sería visible en el tiempo que tarda la información en leerse, no?

**Comment by mpardalm** [comment]
Es solo para la parte visual

**Comment by n1nj4t4nuk1** [comment]
Entiendo. Pues entonces lo único, pasar ahí igualmente toda la carga de datos de ficheros. así simplificamos la actividad principal.
